bash .\\scripts\\AMPTST_V2\\main_raw_96\\AMPTST.sh
#bash .\\scripts\\AMPTST\\main_raw_96\\DLinear.sh
#bash .\\scripts\\AMPTST\\main_raw_96\\iTransformer.sh
#bash .\\scripts\\AMPTST\\main_raw_96\\PatchTST.sh
#bash .\\scripts\\AMPTST\\main_raw_96\\TimeMixer.sh
#bash .\\scripts\\AMPTST\\main_raw_96\\TimesNet.sh
bash .\\scripts\\AMPTST_V2\\ps_96\\AMPTST.sh
#bash .\\scripts\\AMPTST\\ps_96\\DLinear.sh
#bash .\\scripts\\AMPTST\\ps_96\\iTransformer.sh
#bash .\\scripts\\AMPTST\\ps_96\\PatchTST.sh
#bash .\\scripts\\AMPTST\\ps_96\\TimeMixer.sh
#bash .\\scripts\\AMPTST\\ps_96\\TimesNet.sh
bash .\\scripts\\AMPTST_V2\\main_raw_168\\AMPTST.sh
#bash .\\scripts\\AMPTST\\main_raw_168\\DLinear.sh
#bash .\\scripts\\AMPTST\\main_raw_168\\iTransformer.sh
#bash .\\scripts\\AMPTST\\main_raw_168\\PatchTST.sh
#bash .\\scripts\\AMPTST\\main_raw_168\\TimeMixer.sh
#bash .\\scripts\\AMPTST\\main_raw_168\\TimesNet.sh
bash .\\scripts\\AMPTST_V2\\ps_168\\AMPTST.sh
#bash .\\scripts\\AMPTST\\ps_168\\DLinear.sh
#bash .\\scripts\\AMPTST\\ps_168\\iTransformer.sh
#bash .\\scripts\\AMPTST\\ps_168\\PatchTST.sh
#bash .\\scripts\\AMPTST\\ps_168\\TimeMixer.sh
#bash .\\scripts\\AMPTST\\ps_168\\TimesNet.sh